### ISSUE TITLE
Thread endpoint registers with mDS but resources can be read

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-client-example-6lowpan#20]
I can get a Thread endpoint to register with mDS and the resources are listed correctly. When I click "Read" for any of the resources I don't get any results. Checking the console output of the Connected Home app gives a "410 error" for each resource. The endpoint is listed in the mDS admin console, but the endpoint is STALE and no resources are listed.

**Comment by SeppoTakalo** [comment]
Btw. What version of mDS are you running? I had some issues with 2.2 and now I starting to work with demo server on public IPv6. However, I need to use it through DTLS so more work to do.

**Comment by bridadan** [comment]
@SeppoTakalo This was a fairly old issue and I unfortunately don't have the hardware with me to test and replicate. It would have been 2.2 or 2.3 though

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/ONME-1700

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-1992

**Comment by tabarr** [comment]
I am running into the same exact problem with my setup. My setup is the Atmel gateway running static IP connecting to a K64F client unit. The client unit links successfully to the gateway, and I can initially pull information from the client on the HomeConnected browser page. But after a short time, the client stops sending messages and the gateway marks the client as "STALE". Then I start getting 410 errors in HomeConnected. I also see a "ERROR Endpoint is null, unexpected" on the HomeConnected server.
Even though the client is not transmitting every 10 seconds, I can push SW2 and it will send data to the Gateway. The gateway then reports the client as reachable for a time and then stale again. I can keep pushing SW2 and change the state of the client device on the gateway, but the Home Connected server never sees the client until I reset and re-link the client.

The DS version I am running is 2.2.0-660.

**Comment by artokin** [comment]
The example has been changed to use the Device Connector. @tabarr, would you please test by using the mbed Device Connector as it is using the latest mDS.

I'm closing this issue as this happens with previous version of example application and older version of mDS.
