### ISSUE TITLE
6lowpan subghz fails to register with mDS

### ISSUE THREAD

**Issue by bridadan** [ARMmbed/mbed-client-example-6lowpan#21]
Using static setup on Mac OS X 10.10.5

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/ONME-1699

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: ONME-1991

**Comment by SeppoTakalo** [comment]
Cannot be replicated with current version. Most probably IPv6 routing issue.

We do not support the static environment anymore, we use only the public Connector service.
