### ISSUE TITLE
Source file settings unclear

### ISSUE THREAD

**Issue by ErkkiMehtala** [ARMmbed/mbed-client-example-6lowpan#30]
Client side configuration -part:
  There is told in /source/lwm2mclient.cpp line 28 should be MBED_DEVICE_CONNECTOR_URI,
  which is nowhere but there is in same line &MBED_SERVER_ADDRESS. It is not clearly told 
   should it be changed. So should
  &MBED_SERVER_ADDRESS = coap://2607:f0d0:3701:9f::20:5684 ?

Setting Certificate for the application -part
"Copy the created security credentials to file source/security.h."
-> This is not included in any .cpp file of /source

**Comment by simonqhughes** [comment]
ARM Internal Ref: ONME-2013

**Comment by ErkkiMehtala** [comment]
This part is now clear, and issue can be closed.
