### ISSUE TITLE
Documention does not explain how to use the Static GW

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/mbed-client-example-6lowpan#43]
In the markdown documention, there are instructions on how to use the Dynamic configuration, which is great (gateway6LoWPANDynamic.bin , gatewayThreadDynamic.bin)

However, the documentation for the Static configuration and mDS is completely missing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2199

**Comment by artokin** [comment]
A link is added to README that contains instructions how to use static gateways with device server.
