### ISSUE TITLE
non conform ipv6 representation

### ISSUE THREAD

**Issue by thcu-gp** [ARMmbed/mbed-client-example-6lowpan#45]
in file source/mbedclient.cpp the ipv6 address for the embed server is hard coded. The format is incorrect and confusing due to scheme/port mixing and the port/ipv6 colon mixing
- The ipv6 address should be enclosed in square brackets
- The scheme does not match the default coap/coaps ports
     coap should use 5683
     coaps should use 5684

current representation: 
coap://2607:f0d0:2601:52::20:5684

possible corrections
coaps://[2607:f0d0:2601:52::20]:5684
coap://[2607:f0d0:2601:52::20]:5683

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2237

**Comment by anttiylitokola** [comment]
Thanks for your report. We will look into this.

**Comment by mlnx** [comment]
cc @mlnx

**Comment by kmdewaal** [comment]
This is documented in RFC3986 paragraph 3.2.2

>  A host identified by an Internet Protocol literal address, version 6
>    [RFC3513] or later, is distinguished by enclosing the IP literal
>    within square brackets ("[" and "]").  This is the only place where
>    square bracket characters are allowed in the URI syntax.

**Comment by mlnx** [comment]
This has been been fixed on this commit: 56b0a6586046ce057acef2ba9f8574973facc9cd
