### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by z-mayer** [ARMmbed/mbed-client-example-6lowpan#49]
yotta install ---> error: mbed-client-c does not meet specification ^1.0.0 required by sal-stack-nanostack

![Image of Dependency Chain](http://s10.postimg.org/h4fesbhqx/ver_Mismatch.png)

I realize that this is not necessarily an issue with this project, but I'm not sure where to mention this. 
How is yotta supposed to handle such issues in general?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2387

**Comment by teetak01** [comment]
Thank you for reporting! We will look in to this.

**Comment by SeppoTakalo** [comment]
This is now fixed with sal-stack-nanostack v3.0.6.
