### ISSUE TITLE
Default PAN ID?

### ISSUE THREAD

**Issue by javier-moreno-tridonic-com** [ARMmbed/mbed-client-example-6lowpan#53]
The atmel-rf-driver provides functions to set up the PAN ID and the channel, nevertheless I just managed to see the default channel set to 12 but no how the PAN ID is set.

Isn't PAN ID really necessary? Am I missing something?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2436

**Comment by mlnx** [comment]
@SeppoTakalo could you please comment on this?

**Comment by SeppoTakalo** [comment]
Node should pick up the PAN ID from Beacons.
PANID is set on border router (on 6LoWPAN-ND network) and nodes pick up the PANID when they do Beacon scans.

Nanostack allows you to filter the PANID, if you want to use it to identify borderrouters/networks.
