### ISSUE TITLE
Build FRDM-K64F border router 

### ISSUE THREAD

**Issue by catro** [ARMmbed/mbed-client-example-6lowpan#59]
I'm trying to build FRDM-K64F border router. But the page can't be found listed in the readme, https://github.com/ARMmbed/k64f-border-router. Could anyone provide an alternative link?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2479

**Comment by SeppoTakalo** [comment]
Thanks for reporting this.
Repository permissions have now been fixed.

**Comment by catro** [comment]
Thanks!
