### ISSUE TITLE
Update device_server branch

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/mbed-client-example-6lowpan#63]
There are quite many users who are running mDS locally.

The [device_server](https://github.com/ARMmbed/mbed-client-example-6lowpan/tree/device_server) branch has to be updated to fix/improve at least the following:
- Dependencies
- GW binaries
- Documentation (instructions, configurations, and supported features such as Thread router and Sleepy end-node)

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2491

**Comment by SeppoTakalo** [comment]
Commit https://github.com/ARMmbed/mbed-client-example-6lowpan/commit/2c070adec9fbabdb46d44d4477e9980f16a86e73
Updated the device_server branch.
