### ISSUE TITLE
Add PANID / NetworkID to config.json

### ISSUE THREAD

**Issue by mlnx** [ARMmbed/mbed-client-example-6lowpan#64]
Users need to easily modify the PANID and NetworkID configuration of the end-node.

For example, these could be the default values in ```config.json``` to match the BR config

```
"pan-id": "0x0700",
"network-id": "network000000000",
```

**Comment by mlnx** [comment]
@SeppoTakalo please review this

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2494

**Comment by SeppoTakalo** [comment]
Task created to backlog. Closing the issue.
