### ISSUE TITLE
What roles of the Thread network are demonstrated by this demo?

### ISSUE THREAD

**Issue by shahab5** [ARMmbed/mbed-client-example-6lowpan#77]
HI,

I need to understand what roles are demonstrated by this example. Since there are only two modules used here, Border Router and Joiner Router.

**Question**
 Is the Thread Gateway (Border) Router acting as Leader and Commisioner as well? 

Kindly, help me understand.

Thanks,
Shahab

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-2647

**Comment by artokin** [comment]
Hi,

The first router enabled device started will begin as a Leader of the Thread network (End Device can't be a Leader).

In this example we have two devices and they are using static configuration to establish a Thread network. When static configuration is used then required network parameters are already known by the joining device and therefore commissioning process is not needed.

BR,
Arto

**Comment by shahab5** [comment]
Thank you very much for the explanation.

Is there a plan to have a Thread demo with commissioning process?

Regards,
Shahab

**Comment by mlnx** [comment]
Shahab,

> Is there a plan to have a Thread demo with commissioning process?

Yes, there will be a demo at some point in the future.
If you are an mbed Partner, please contact your Partner Lead for more information.

Best regards,
Marcelo

**Comment by shahab5** [comment]
Thank you all.
Closing this issue.

Regards,
Shahab
